const router = require('express').Router();
const { GoogleGenerativeAI } = require('@google/generative-ai');
const Quiz = require('../models/Quiz');

// Initialize AI (Make sure to add GEMINI_API_KEY to your backend .env file)
const genAI = new GoogleGenerativeAI(process.env.GEMINI_API_KEY);

router.post('/generate', async (req, res) => {
  try {
    const { lessonId, lessonContent } = req.body;

    if (!lessonContent) {
      return res.status(400).json({ error: "Lesson content is required for AI generation." });
    }

    const model = genAI.getGenerativeModel({ model: "gemini-2.5-flash" });

    // The Master Prompt: Forcing the AI to output exact JSON for our schema
    const prompt = `
      You are an expert curriculum designer. Read the following lesson content and generate a 12-question adaptive quiz. 
      Output the quiz strictly as a JSON array of question objects. Do not include markdown formatting like \`\`\`json.
      
      Requirements:
      1. Create exactly 12 questions.
      2. Vary the difficulties: 4 Easy (difficulty: 1), 4 Medium (difficulty: 2), 4 Hard (difficulty: 3).
      3. Use 4 different question types: 'single' (1 correct option), 'multiple' (2+ correct options), 'fill' (fill in the blank), and 'match' (matching pairs).
      
      JSON Object Structure per question type:
      - 'single' or 'multiple': { "text": "...", "type": "single", "difficulty": 1, "options": [{ "text": "...", "isCorrect": true/false }] }
      - 'fill': { "text": "The powerhouse of the cell is the ____.", "type": "fill", "difficulty": 2, "correctAnswerText": "mitochondria" }
      - 'match': { "text": "Match the terms", "type": "match", "difficulty": 3, "options": [{ "matchLeft": "Term 1", "matchRight": "Definition 1" }] }
      
      Lesson Content to evaluate:
      "${lessonContent}"
    `;

    // Call the AI
    const result = await model.generateContent(prompt);
    let aiResponse = result.response.text();

    // Clean up AI output to ensure perfect JSON parsing
    aiResponse = aiResponse.replace(/```json/g, '').replace(/```/g, '').trim();
    const generatedQuestions = JSON.parse(aiResponse);

    // Save to MongoDB
    const newQuiz = new Quiz({
      lessonId: lessonId,
      questions: generatedQuestions
    });

    const savedQuiz = await newQuiz.save();
    
    res.status(201).json({
      message: "Adaptive Quiz successfully generated by AI!",
      quiz: savedQuiz
    });

  } catch (err) {
    console.error("AI Generation Error:", err);
    res.status(500).json({ error: "Failed to generate AI quiz.", details: err.message });
  }
});

// Fetch a quiz for a specific lesson
router.get('/:lessonId', async (req, res) => {
  try {
    const quiz = await Quiz.findOne({ lessonId: req.params.lessonId });
    if (!quiz) return res.status(404).json({ error: "No quiz found for this lesson." });
    res.status(200).json(quiz);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

module.exports = router;